// Code generated by gocontroller-gen; DO NOT EDIT.

package main

import "github.com/emmybxt/go-controller/v2/gocontroller"

func (c *BookController) ControllerMetadata() gocontroller.ControllerMetadata {
	return gocontroller.ControllerMetadata{Prefix: "/books",
		Routes: []gocontroller.Route{
			gocontroller.GET("/featured", c.Featured, FeaturedHeader()),
			gocontroller.GET("/:id", c.Get),
		},
	}
}
