// Code generated by gocontroller-gen; DO NOT EDIT.

package main

import "github.com/emmybxt/go-controller/gocontroller"

func init() {
	gocontroller.RegisterGeneratedControllerMetadata((*SomethingController)(nil), gocontroller.ControllerMetadata{
		Prefix: "",
		Routes: []gocontroller.RouteMetadata{
			gocontroller.GET("/hello", "Hello"),
			gocontroller.GET("/something/:id", "GetSomething"),
			gocontroller.POST("/something", "CreateSomething", ExampleAPIKeyMiddleware()),
			gocontroller.POST("/upload", "Upload", ExampleAPIKeyMiddleware()),
			gocontroller.GET("/items", "ListItems"),
			gocontroller.GET("/protected", "Protected"),
			gocontroller.GET("/session", "SessionDemo"),
		},
	})
}
