// Code generated by gocontroller-gen; DO NOT EDIT.

package main

import "github.com/emmybxt/gocontroller/gocontroller"

func init() {
	gocontroller.RegisterGeneratedControllerMetadata((*SomethingController)(nil), gocontroller.ControllerMetadata{
		Prefix: "",
		Routes: []gocontroller.RouteMetadata{
			gocontroller.GET("/hello", "Hello"),
			gocontroller.GET("/something/:id", "GetSomething"),
			gocontroller.POST("/something", "CreateSomething", APIKeyMiddleware("local-dev-key")),
		},
	})
}
