// Code generated by gocontroller-gen; DO NOT EDIT.

package main

import "github.com/emmybxt/go-controller/v2/gocontroller"

func (c *AccountsController) ControllerMetadata() gocontroller.ControllerMetadata {
	return accountsController.MustBind(
		gocontroller.POST("", c.CreateAccount),
		gocontroller.GET("/:accountId", c.GetAccount),
	)
}
