package main

import (
	"fmt"
	"go/format"
	"strings"
)

func generateCode(pkg string, controllers []controllerInfo) ([]byte, error) {
	var b strings.Builder
	fmt.Fprintf(&b, "// Code generated by gocontroller-gen; DO NOT EDIT.\n\npackage %s\n\n", pkg)
	b.WriteString("import \"github.com/emmybxt/go-controller/v2/gocontroller\"\n\n")
	for _, controller := range controllers {
		writeController(&b, controller)
	}
	return format.Source([]byte(b.String()))
}

func writeController(b *strings.Builder, controller controllerInfo) {
	fmt.Fprintf(b, "func (c *%s) ControllerMetadata() gocontroller.ControllerMetadata {\n", controller.Name)
	fmt.Fprintf(b, "return gocontroller.ControllerMetadata{Prefix: %q,\n", controller.Prefix)
	if len(controller.Middleware) > 0 {
		fmt.Fprintf(b, "Middleware: []any{%s},\n", strings.Join(controller.Middleware, ", "))
	}
	b.WriteString("Routes: []gocontroller.Route{\n")
	for _, route := range controller.Routes {
		fmt.Fprintf(b, "gocontroller.%s(%q, c.%s", route.Method, route.Path, route.Handler)
		for _, middleware := range route.Middleware {
			fmt.Fprintf(b, ", %s", middleware)
		}
		b.WriteString("),\n")
	}
	b.WriteString("},\n}\n}\n\n")
}
