package main

import (
	"flag"
	"fmt"
	"go/ast"
	"go/parser"
	"go/token"
	"os"
	"path/filepath"
	"regexp"
	"sort"
	"strings"
)

type controllerInfo struct {
	Name       string
	Prefix     string
	Middleware []string
	Routes     []routeInfo
}

type routeInfo struct {
	Method     string
	Path       string
	Handler    string
	Middleware []string
}

func main() {
	var dir string
	var out string
	flag.StringVar(&dir, "dir", ".", "package directory to scan")
	flag.StringVar(&out, "out", "zz_gocontroller_routes.gen.go", "output file name")
	flag.Parse()

	pkgName, controllers, err := parseControllers(dir)
	if err != nil {
		exitf("parse controllers: %v", err)
	}
	if len(controllers) == 0 {
		exitf("no annotated controllers found in %s", dir)
	}

	code := generateCode(pkgName, controllers)
	outPath := filepath.Join(dir, out)
	if err := os.WriteFile(outPath, []byte(code), 0o644); err != nil {
		exitf("write %s: %v", outPath, err)
	}
}

func parseControllers(dir string) (string, []controllerInfo, error) {
	fset := token.NewFileSet()
	pkgs, err := parser.ParseDir(fset, dir, func(info os.FileInfo) bool {
		name := info.Name()
		if strings.HasSuffix(name, ".gen.go") {
			return false
		}
		return strings.HasSuffix(name, ".go")
	}, parser.ParseComments)
	if err != nil {
		return "", nil, err
	}

	if len(pkgs) == 0 {
		return "", nil, fmt.Errorf("no package found")
	}

	var pkg *ast.Package
	for _, p := range pkgs {
		pkg = p
		break
	}

	controllers := map[string]*controllerInfo{}
	for _, file := range pkg.Files {
		for _, decl := range file.Decls {
			switch d := decl.(type) {
			case *ast.GenDecl:
				if d.Tok != token.TYPE {
					continue
				}
				for _, spec := range d.Specs {
					ts, ok := spec.(*ast.TypeSpec)
					if !ok {
						continue
					}
					_, isStruct := ts.Type.(*ast.StructType)
					if !isStruct {
						continue
					}
					tags := extractTags(ts.Doc, d.Doc)
					controllerTag, ok := tags["Controller"]
					if !ok {
						continue
					}
					c := &controllerInfo{Name: ts.Name.Name, Prefix: trimQuotes(controllerTag)}
					if use, ok := tags["Use"]; ok {
						c.Middleware = parseUseList(use)
					}
					controllers[c.Name] = c
				}
			case *ast.FuncDecl:
				if d.Recv == nil || d.Name == nil {
					continue
				}
				recvType := receiverName(d.Recv)
				if recvType == "" {
					continue
				}
				ctrl, ok := controllers[recvType]
				if !ok {
					continue
				}
				tags := extractTags(d.Doc)
				for _, verb := range []string{"Get", "Post", "Put", "Delete"} {
					raw, ok := tags[verb]
					if !ok {
						continue
					}
					rt := routeInfo{Method: strings.ToUpper(verb), Path: trimQuotes(raw), Handler: d.Name.Name}
					if use, ok := tags["Use"]; ok {
						rt.Middleware = parseUseList(use)
					}
					ctrl.Routes = append(ctrl.Routes, rt)
				}
			}
		}
	}

	list := make([]controllerInfo, 0, len(controllers))
	for _, c := range controllers {
		if len(c.Routes) == 0 {
			continue
		}
		list = append(list, *c)
	}
	sort.Slice(list, func(i, j int) bool { return list[i].Name < list[j].Name })
	return pkg.Name, list, nil
}

func extractTags(groups ...*ast.CommentGroup) map[string]string {
	out := map[string]string{}
	re := regexp.MustCompile(`^@([A-Za-z]+)\((.*)\)$`)
	for _, group := range groups {
		if group == nil {
			continue
		}
		for _, c := range group.List {
			line := strings.TrimSpace(strings.TrimPrefix(c.Text, "//"))
			if !strings.HasPrefix(line, "@") {
				continue
			}
			m := re.FindStringSubmatch(line)
			if len(m) != 3 {
				continue
			}
			out[m[1]] = strings.TrimSpace(m[2])
		}
	}
	return out
}

func receiverName(recv *ast.FieldList) string {
	if recv == nil || len(recv.List) == 0 {
		return ""
	}
	t := recv.List[0].Type
	switch v := t.(type) {
	case *ast.Ident:
		return v.Name
	case *ast.StarExpr:
		if id, ok := v.X.(*ast.Ident); ok {
			return id.Name
		}
	}
	return ""
}

func trimQuotes(s string) string {
	s = strings.TrimSpace(s)
	s = strings.TrimPrefix(s, "\"")
	s = strings.TrimSuffix(s, "\"")
	s = strings.TrimPrefix(s, "`")
	s = strings.TrimSuffix(s, "`")
	return s
}

func parseUseList(s string) []string {
	parts := strings.Split(s, ",")
	out := make([]string, 0, len(parts))
	for _, p := range parts {
		p = strings.TrimSpace(p)
		if p == "" {
			continue
		}
		out = append(out, p)
	}
	return out
}

func generateCode(pkg string, controllers []controllerInfo) string {
	var b strings.Builder
	b.WriteString("// Code generated by gocontroller-gen; DO NOT EDIT.\n")
	b.WriteString("\n")
	b.WriteString("package ")
	b.WriteString(pkg)
	b.WriteString("\n\n")
	b.WriteString("import \"github.com/emmybxt/go-controller/gocontroller\"\n\n")
	b.WriteString("func init() {\n")
	for _, c := range controllers {
		b.WriteString("\tgocontroller.RegisterGeneratedControllerMetadata((*")
		b.WriteString(c.Name)
		b.WriteString(")(nil), gocontroller.ControllerMetadata{\n")
		b.WriteString("\t\tPrefix: \"")
		b.WriteString(escape(c.Prefix))
		b.WriteString("\",\n")

		if len(c.Middleware) > 0 {
			b.WriteString("\t\tMiddleware: []gocontroller.Middleware{")
			for i, mw := range c.Middleware {
				if i > 0 {
					b.WriteString(", ")
				}
				b.WriteString(mw)
			}
			b.WriteString("},\n")
		}

		b.WriteString("\t\tRoutes: []gocontroller.RouteMetadata{\n")
		for _, r := range c.Routes {
			b.WriteString("\t\t\tgocontroller.")
			b.WriteString(r.Method)
			b.WriteString("(\"")
			b.WriteString(escape(r.Path))
			b.WriteString("\", \"")
			b.WriteString(r.Handler)
			b.WriteString("\"")
			if len(r.Middleware) > 0 {
				b.WriteString(", ")
				for i, mw := range r.Middleware {
					if i > 0 {
						b.WriteString(", ")
					}
					b.WriteString(mw)
				}
			}
			b.WriteString("),\n")
		}
		b.WriteString("\t\t},\n")
		b.WriteString("\t})\n")
	}
	b.WriteString("}\n")
	return b.String()
}

func escape(s string) string {
	s = strings.ReplaceAll(s, "\\", "\\\\")
	s = strings.ReplaceAll(s, "\"", "\\\"")
	return s
}

func exitf(format string, args ...any) {
	_, _ = fmt.Fprintf(os.Stderr, format+"\n", args...)
	os.Exit(1)
}
